"""empty message

Revision ID: b43e63da3910
Revises: 147d43843948
Create Date: 2020-12-08 20:18:23.255570

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b43e63da3910'
down_revision = '147d43843948'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_column('comment_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comment_date', sa.DATETIME(), nullable=True))

    # ### end Alembic commands ###
